- name: backend configuration
  hosts: backend
  connection: local
  become: yes
  tasks:
  - name: disable default nodjs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: useradd
    ansible.builtin.user:
      name: expense

  - name: Create a app directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
    
  - name: Download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  
  - name: Extract the code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes